//
// Created by User on 08/09/2025.
//

#ifndef ANEAWESOMEUTILSWINDOWS_WINDOWSFILTERINPUTS_H
#define ANEAWESOMEUTILSWINDOWS_WINDOWSFILTERINPUTS_H
void StartHooksIfNeeded();
void StopHooks();
#endif //ANEAWESOMEUTILSWINDOWS_WINDOWSFILTERINPUTS_H